// Autogenerated by Thrift Compiler (1.0.0-dev)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"git.apache.org/thrift.git/lib/go/thrift"
  "./gen-go/service"
  "../nsq_thrift"
  "log"
)

type TestImpl struct {
 foo string
}

func (t *TestImpl) Foo(bar string) error {
  log.Println("Message received:", bar)
  return nil
}

func main() {
  nsq_server, err := nsq_thrift.NewTServerNSQ("foo", "bar", nsq_thrift.NSQD, "127.0.0.1:4150")

  if err != nil {
    println(err)
  }

  server := thrift.NewTSimpleServer4(
    service.NewTestProcessor(&TestImpl{}),
    nsq_server,
    thrift.NewTTransportFactory(),
    thrift.NewTJSONProtocolFactory(),
  )
  server.Serve()
}
